# Generated by Django 5.2.6 on 2025-09-15 18:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="phone_number_verified",
            new_name="is_phone_number_verified",
        ),
    ]
